src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Is_Synced__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Synced</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Processed_By_Queue__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed By Queue</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AddressQueueableProcessor.cls
/**
 * Created by solol on 22.12.2019.
 */

public with sharing class AddressQueueableProcessor implements Queueable{

    private List<Id> ids;

    public AddressQueueableProcessor(List<Id> ids){
        this.ids = ids;
    }

    public void execute(QueueableContext context) {
        List<Contact> contacts = [SELECT Is_Synced__c, Processed_By_Queue__c FROM Contact WHERE AccountId in :ids];
        for (Contact contact : contacts){
            contact.Is_Synced__c = false;
            contact.Processed_By_Queue__c = true;
        }
        update contacts;
    }


}